// Code generated by MockGen. DO NOT EDIT.
// Source: ./grpc/data_source.go

// Package grpc is a generated GoMock package.
package grpc

import (
	reflect "reflect"

	proto "github.com/buildwithgrove/path/envoy/auth_server/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockDataSource is a mock of DataSource interface.
type MockDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockDataSourceMockRecorder
}

// MockDataSourceMockRecorder is the mock recorder for MockDataSource.
type MockDataSourceMockRecorder struct {
	mock *MockDataSource
}

// NewMockDataSource creates a new mock instance.
func NewMockDataSource(ctrl *gomock.Controller) *MockDataSource {
	mock := &MockDataSource{ctrl: ctrl}
	mock.recorder = &MockDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataSource) EXPECT() *MockDataSourceMockRecorder {
	return m.recorder
}

// FetchInitialData mocks base method.
func (m *MockDataSource) FetchInitialData() (*proto.InitialDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchInitialData")
	ret0, _ := ret[0].(*proto.InitialDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchInitialData indicates an expected call of FetchInitialData.
func (mr *MockDataSourceMockRecorder) FetchInitialData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchInitialData", reflect.TypeOf((*MockDataSource)(nil).FetchInitialData))
}

// GetUpdatesChan mocks base method.
func (m *MockDataSource) GetUpdatesChan() (<-chan *proto.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatesChan")
	ret0, _ := ret[0].(<-chan *proto.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdatesChan indicates an expected call of GetUpdatesChan.
func (mr *MockDataSourceMockRecorder) GetUpdatesChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatesChan", reflect.TypeOf((*MockDataSource)(nil).GetUpdatesChan))
}
