name: Build image and push to ghcr.io

on:
  # workflow_run:
  #   workflows: ["Path Auth Data Server tests"]
  #   types:
  #     - completed
  #   branches:
  #     - main
  # workflow_dispatch: # Added to enable manual trigger via GitHub UI
  push:
    branches: [github-actions]
  pull_request:
    branches: [github-actions]

jobs:
  release-on-push:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ github.token }}
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          release_body: ":rocket: Release Notes !:fireworks: "
          use_github_release_notes: true

  build-and-push:
    runs-on: "ubuntu-22.04"
    needs: [release-on-push]
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        with:
          images: |
            ghcr.io/buildwithgrove/path-auth-data-server
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=tag,suffix=-rc
            type=sha,format=short,suffix=-rc
            type=ref,event=branch,pattern=latest
            latest 

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: IMAGE_TAG=${{ steps.meta.outputs.version }}
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
